name: learnk
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

# packages
dependencies:
  flutter:
    sdk: flutter

# icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2


# statemanagement
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:

 
  uses-material-design: true

  
  assets:
    - assets/images/
 